baseurl: ''
email: hello@chriswilding.co.uk
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - lambda.js
  - lambda.zip
  - terraform.tf
  - vendor
markdown: kramdown
plugins:
  - jekyll-sitemap
sass:
  style: compressed
title: Chris Wilding
url: 'http://www.chriswilding.co.uk'
usernames:
  github:  ChrisWilding
  linkedin: ChrisWildingUK
  twitter: ChrisWildingUK
