baseurl: ''
email: hello@chriswilding.co.uk
markdown: kramdown
sass:
  style: compressed
title: Chris Wilding
url: 'http://www.chriswilding.co.uk'
usernames:
  github:  ChrisWilding
  linkedin: ChrisWildingUK
  twitter: ChrisWildingUK
