# Site settings
title: Chris Wilding
email: hello@chriswilding.co.uk
description: >
  This is the personal website of Chris Wilding
baseurl: ''
url: 'http://chriswilding.co.uk'
github_username:  ChrisWilding
linkedin_username: ChrisWildingUK
twitter_username: ChrisWildingUK

# Build settings
markdown: kramdown
