# Site settings
title: Enterprise Ruby on Rails application developer
email: hello@chriswilding.co.uk
description: >
  This is the personal website of Chris Wilding
baseurl: ''
url: 'http://chriswilding.co.uk'
twitter_username: ChrisWildingUK
github_username:  ChrisWilding

# Build settings
markdown: kramdown
