version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/web

    steps:
      - checkout
      - run:
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm test
